# IGE-122998 - Pedro Soares
# IGE-122978 - Luísa Almas
# Code smell: Long Parameter List

name: Qodana Code Analysis

on:
  push:
    branches:
      - main
      - Pedro_tarefa2

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.1
        with:
          linter: jetbrains/qodana-jvm
