# IGE-122998 - Pedro Soares

name: Qodana Code Analysis

on:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: --linter jetbrains/qodana-jvm
